import Header from "@/components/Header/Header";
import { supabase } from "@/lib/supabase-server/supabase";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import "./globals.css";

const cabinetGrotesk = localFont({
  src: [
    {
      path: "../assets/cabinet-grotesk/CabinetGrotesk-Variable.woff2",
    },
    {
      path: "../assets/cabinet-grotesk/CabinetGrotesk-Variable.woff",
    },
    {
      path: "../assets/cabinet-grotesk/CabinetGrotesk-Variable.ttf",
    },
  ],
  display: "swap",
  style: "normal",
  variable: "--font-cabinet",
});

const satoshi = localFont({
  src: [
    {
      path: "../assets/satoshi/Satoshi-Variable.woff2",
    },
    {
      path: "../assets/satoshi/Satoshi-Variable.woff",
    },
    {
      path: "../assets/satoshi/Satoshi-Variable.ttf",
    },
  ],
  display: "swap",
  style: "normal",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data } = await supabase.auth.getUser();
  return (
    <html lang="en">
      <body
        className={`${cabinetGrotesk.variable} font-satoshi text-foreground ${satoshi.variable}`}
      >
        <Header user={data.user} />
        {children}
        <Toaster
          toastOptions={{
            style: {
              background: "#ffffff",
              color: "#000000",
              fontFamily: "var(--font-satoshi)",
              borderColor: "#000000",
            },
          }}
        />
      </body>
    </html>
  );
}
